server:
  port: 9131

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/数据库名?useUnicode=true&characterEncoding=utf-8&serveTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

Logging:
  level:
    com.rabbiter: debug

aliyun:
  sms:
    accessKeyId: aliyun_accessKeyId
    accessKeySecret: aliyun_accessKeySecret
    signName: 短信发送的signName
    templateCode: 短信发送的templateCode